image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:

  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
